### ISSUE TITLE
Could you kindly share the SASRec-[Dataset]-0.pth files?

### ISSUE THREAD

**Issue by littlemilkwu** [nancheng58/On-the-User-Behavior-Leakage-from-Recommender-System-Exposure#2]
https://github.com/nancheng58/On-the-User-Behavior-Leakage-from-Recommender-System-Exposure/blob/9fc178260694f19501360d4b0a151efd434d7934/run_protection.py#L95-L96

Could you kindly share the SASRec-[Dataset]-0.pth files with me so that I can reproduce your outstanding work? Thanks a lot!

![image](https://github.com/nancheng58/On-the-User-Behavior-Leakage-from-Recommender-System-Exposure/assets/44579618/e0692b61-15ea-4c23-a73a-95062af137c5)

**Comment by nancheng58** [comment]
Thanks for your kindly suggestion! Both SASRec model files were already uploaded just now.
